default:
  tags:
    - ${PIPELINE_TAG}

stages:
  - build

build-go:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10.16
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:18.09.7-dind
      alias: docker
  stage: build
  script:
    - REPO=registry.gitlab.com/devopsrt71/container-images
    - IMAGE_TAG="golang.1.21-${CI_PIPELINE_ID}"
    - IMAGE=${REPO}/${IMAGE_TAG}
    - docker build -t ${IMAGE} -f Dockerfile.golang.1.21 .    
    - docker push
